config/routes.rb
Rails.application.routes.draw do


  get 'home/main'

  get 'home/itemlist'

  get 'home/detailinfo'
  
  post '/tinymce_assets' => 'tinymce_assets#create'

  devise_for :users
  root "home#main"
  resources :posts do
    post "/like", to: "likes#like_toggle"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  has_and_belongs_to_many :users

  has_many :reviews
  has_many :users, through: :reviews
end

app/models/items_user.rb
class ItemsUser < ApplicationRecord
  belongs_to :item
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user

    has_many :liked_users, through: :likes, source: :use

    has_many :likes

  #  mount_uploader :file, ImageUploader

    def self.search(query)
      self.where("title || content LIKE ?","%#{query}%")
    end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_and_belongs_to_many :items

  has_many :reviews
  has_many :items, through: :reviews

  # def is_like?(post)
  #   Like.find_by(user_id: self.id, post_id: post.id).present?
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def main
    @posts = Post.all
  end

  def itemlist

  end

  def detailinfo

  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    before_action :authenticate_user!
    def like_toggle
        like = Like.find_by(user_id: current_user.id, post_id: params[:post_id])
        if like.nil?
            Like.create(user_id: current_user.id, post_id: params[:post_id])
        else
            like.destroy
        end
            redirect_to posts_path
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :is_owner?, only: [:edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    # @posts = Post.all
    if params[:search]
      @posts = Post.search(params[:search])
    else
      @posts = Post.order(created_at: :DESC).page(params[:page]).per(10)
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end


  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :file, :user_id)
    end

  def is_owner?
    if current_user != @post.user
      redirect_to post_path(@post)
    end
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:user_id, :coffee_id, :title, :content, :image, :location, :like_count)
    end
end

app/controllers/tinymce_assets_controller.rb
class TinymceAssetsController < ApplicationController
  def create
    # Take upload from params[:file] and store it somehow...
    # Optionally also accept params[:hint] and consume if needed
    post = Post.create params.permit(:file)

    render json: {
      image: {
        url: post.file.url
      }
    }, content_type: "text/html"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/elfinder_helper.rb
module ElfinderHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/home/detailinfo.html.erb
<div id="menu">
    <nav>
      <ul>
        <li><a href="#">스타벅스</a></li>
        <li><a href="#">이디야</a></li>
        <li><a href="#">커피빈</a></li>
        <li><a href="#">투썸플레이스</a></li>
        <li><a href="#">엔제리너스</a></li>
      </ul>
    </nav>
  </div>
  <div id="line">
  </div>
<p id="notice"><%= notice %></p>

<h1 style="border-bottom:2px solid black; padding-bottom:10px;">브랜드 - 제품 (DB사용)</h1>

<div style="width:1000px; height:800px; margin-left:200px;">
  <div style="width:400px; height:800px; float:left;" id="detail-info">
    <img src="https://s3.ap-northeast-2.amazonaws.com/coffeeinfo/uploads/orangelatte_bback.png" style="width:380px; height:280px; margin-top:20px;">
    <div style="margin-top:15px;">
      <h5>현장이미지</h5>
      <div>
        <img src="https://s3.ap-northeast-2.amazonaws.com/coffeeinfo/uploads/orangelatte_bback.png" style="width:65px; height:65px; margin-left:5px;">
        <img src="https://s3.ap-northeast-2.amazonaws.com/coffeeinfo/uploads/orangelatte_bback.png" style="width:65px; height:65px; margin-left:5px;">
        <img src="https://s3.ap-northeast-2.amazonaws.com/coffeeinfo/uploads/orangelatte_bback.png" style="width:65px; height:65px; margin-left:5px;">
        <img src="https://s3.ap-northeast-2.amazonaws.com/coffeeinfo/uploads/orangelatte_bback.png" style="width:65px; height:65px; margin-left:5px;">
        <img src="https://s3.ap-northeast-2.amazonaws.com/coffeeinfo/uploads/orangelatte_bback.png" style="width:65px; height:65px; margin-left:5px;">
      </div>
    </div>
    <div style="margin-top:15px; height:40px;">
      <p style="width:150px; margin-left:40px; float:left; font-size:20px;">●좋아요(DB)</p><p style="width:150px; margin-left:15px; float:left; font-size:20px;">●싫어요(DB)</p>
    </div>
    <div style="margin-top:15px;">
      <h4>댓글</h4>
      <form action="#">
        <input type="text"><input type="button" value="등록" style="width:50px;">
      </form>
      <div style="margin-top:15px;">
        <p>각 댓글이 보일 부분입니다! DB작업 이후 반복문으로!</p>
        <p>각 댓글이 보일 부분입니다! DB작업 이후 반복문으로!</p>
        <p>각 댓글이 보일 부분입니다! DB작업 이후 반복문으로!</p>
        <p>각 댓글이 보일 부분입니다! DB작업 이후 반복문으로!</p>
        <p>각 댓글이 보일 부분입니다! DB작업 이후 반복문으로!</p>
      </div>
    </div>
  </div>
  <div style="float:left; width:400px; height:800px; margin-top:20px; margin-left:80px;">
    <div>
      <h3>● 제품명(DB사용)</h3>
      <p>간략한 설명이 들어 갈 부분입니다. DB를 사용하겠지요 아마도?? 디비에 저장된 설명을 가져오기로!</p>
      <p>tall : 6000원(DB)</p>
      <p>grande : 7000원(DB)</p>
      <p>venti : 8000원(DB)</p>
    </div>
    <div style="margin-top:35px;">
      <h4>● 추천멘트(DB)</h4>
      <p>여기에도 간략한 코멘트가 들어갈 것이고,,,,,,,,, 이것 또한 디비에 저장된걸 가져오는 방식으로 진행! 주석처럼 사용했슴다.</p>
    </div>
    <div style="margin-top:35px;">
          <h2>매장위치</h2>
          <div id="map" style="width:300px; height:200px; float:left;"></div>
          <script>
          function initMap() {
            var uluru = {lat: 37.507040, lng: 127.033747};
            var map = new google.maps.Map(document.getElementById('map'), {
              zoom: 15,
              center: uluru
            });
            var marker = new google.maps.Marker({
              position: uluru,
              map: map
            });
          }
        </script>
        <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDtC8JQTzZfMZle3SdEep0lBmhYFFOECw8&callback=initMap"
        async defer></script>
    </div>

  </div>

</div>

app/views/home/itemlist.html.erb
<div class="container">
  <div class="popular">
    <h3>이달의 인기상품</h3>
    <img src="https://s3.ap-northeast-2.amazonaws.com/coffeeinfo/uploads/americano_bback.png" id="popularMenu">
  </div>
  <div id="brandmenu">
    <div class="brands">
      <p><img src="https://s3.ap-northeast-2.amazonaws.com/coffeeinfo/uploads/bback.png"></p>
      <div class="brand">
        <div style="float:left" class="itemname"><img src="https://s3.ap-northeast-2.amazonaws.com/coffeeinfo/uploads/americano_bback.png"><br><p style="text-align:center">아메리카노</p></div>
        <div style="float:left" class="itemname"><img src="https://s3.ap-northeast-2.amazonaws.com/coffeeinfo/uploads/balatte_bback.png"><br><p style="text-align:center">바닐라 라떼</p></div>
        <div style="float:left" class="itemname"><img src="https://s3.ap-northeast-2.amazonaws.com/coffeeinfo/uploads/orangelatte_bback.png"><br><p style="text-align:center">오렌지 라떼</p></div>
        <div style="float:left" class="itemname"><img src="https://s3.ap-northeast-2.amazonaws.com/coffeeinfo/uploads/sweetlatte_bback.png"><br><p style="text-align:center">연유라떼</p></div>
      </div>
    </div>
    <div class="brands">
      <p><img src="https://s3.ap-northeast-2.amazonaws.com/coffeeinfo/uploads/%EC%8A%A4%ED%83%80%EB%B2%85%EC%8A%A4.jpg"></p>
      <div class="brand">
        <div style="float:left" class="itemname"><img src="https://s3.ap-northeast-2.amazonaws.com/coffeeinfo/uploads/%EB%82%98%EC%9D%B4%ED%8A%B8%EB%A1%9C+%EC%BD%9C%EB%93%9C%EB%B8%8C%EB%A3%A8_%EC%8A%A4%EB%B2%85.jpg"><br><p style="text-align:center">나이트로</p> <p style="text-align:center">콜드브루</p></div>
        <div style="float:left" class="itemname"><img src="https://s3.ap-northeast-2.amazonaws.com/coffeeinfo/uploads/%EC%95%84%EC%9D%B4%EC%8A%A4+%EC%B9%B4%ED%8E%98+%EC%95%84%EB%A9%94%EB%A6%AC%EC%B9%B4%EB%85%B8_%EC%8A%A4%EB%B2%85.jpg"><br><p style="text-align:center">아이스카페</p><p style="text-align:center">아메리카노</p></div>
        <div style="float:left" class="itemname"><img src="https://s3.ap-northeast-2.amazonaws.com/coffeeinfo/uploads/%EC%97%90%EC%8A%A4%ED%94%84%EB%A0%88%EC%86%8C+%EB%A7%88%EB%81%BC%EC%95%84%EB%98%90_%EC%8A%A4%EB%B2%85.jpg"><br><p style="text-align:center">에스프레소</p><p style="text-align:center"> 마끼아또</p></div>
        <div style="float:left" class="itemname"><img src="https://s3.ap-northeast-2.amazonaws.com/coffeeinfo/uploads/%EC%97%90%EC%8A%A4%ED%94%84%EB%A0%88%EC%86%8C+%EC%BD%98+%ED%8C%8C%EB%83%90_%EC%8A%A4%EB%B2%85.jpg"><br><p style="text-align:center">에스프레소</p><p style="text-align:center"> 콘파냐</p></div>
      </div>
    </div>
    <div class="brands">
      <p><img src="https://s3.ap-northeast-2.amazonaws.com/coffeeinfo/uploads/%EC%9A%94%EA%B1%B0%ED%94%84%EB%A0%88%EC%86%8C.gif"></p>
      <div class="brand">
        <div style="float:left" class="itemname"><img src="https://s3.ap-northeast-2.amazonaws.com/coffeeinfo/uploads/%EB%8B%88%ED%8A%B8%EB%A1%9C%EC%BD%9C%EB%93%9C%EB%B8%8C%EB%A3%A8_%EC%9A%94%ED%94%84.jpg"><br><p style="text-align:center">니트로</p><p style="text-align:center"> 콜드브루</p></div>
        <div style="float:left" class="itemname"><img src="https://s3.ap-northeast-2.amazonaws.com/coffeeinfo/uploads/%EB%B0%94%EB%8B%90%EB%9D%BC%EB%9D%BC%EB%96%BC%EC%95%84%EC%9D%B4%EC%8A%A4_%EC%9A%94%ED%94%84.jpg"><br><p style="text-align:center">바닐라라떼</p><p style="text-align:center"> 아이스</p></div>
        <div style="float:left" class="itemname"><img src="https://s3.ap-northeast-2.amazonaws.com/coffeeinfo/uploads/%EC%95%84%EC%9D%B4%EC%8A%A4+%EC%B9%B4%ED%8E%98%EB%AA%A8%EC%B9%B4_%EC%9A%94%ED%94%84.jpg"><br><p style="text-align:center">아이스</p><p style="text-align:center">카페모카</p></div>
        <div style="float:left" class="itemname"><img src="https://s3.ap-northeast-2.amazonaws.com/coffeeinfo/uploads/%EC%95%84%EC%9D%B4%EC%8A%A4+%EC%B9%B4%ED%91%B8%EC%B9%98%EB%85%B8_%EC%9A%94%ED%94%84.jpg"><br><p style="text-align:center">아이스</p><p style="text-align:center">카푸치노</p></div>
        <div style="float:left" class="itemname"><img src="https://s3.ap-northeast-2.amazonaws.com/coffeeinfo/uploads/%EC%95%84%EC%9D%B4%EC%8A%A4+%ED%99%94%EC%9D%B4%ED%8A%B8+%EC%B9%B4%ED%8E%98%EB%AA%A8%EC%B9%B4_%EC%9A%94%ED%94%84.jpg"><br><p style="text-align:center">아이스화이트</p><p style="text-align:center">카페모카</p></div>
      </div>
    </div>
    <div class="brands">
      <p><img src="https://s3.ap-northeast-2.amazonaws.com/coffeeinfo/uploads/%EC%BB%A4%ED%94%BC%EB%B9%88.jpg"></p>
      <div class="brand">
        <div style="float:left" class="itemname"><img src="https://s3.ap-northeast-2.amazonaws.com/coffeeinfo/uploads/%EB%AA%A8%EC%B9%B4+%EC%95%84%EC%9D%B4%EC%8A%A4+%EB%B8%94%EB%A0%8C%EB%94%94%EB%93%9C+S_%EC%BB%A4%ED%94%BC%EB%B9%88.jpg"><br><p style="text-align:center">모카 아이스</p><p style="text-align:center">블렌디드</p></div>
        <div style="float:left" class="itemname"><img src="https://s3.ap-northeast-2.amazonaws.com/coffeeinfo/uploads/%EC%BA%90%EB%9F%AC%EB%A9%80+%EC%95%84%EC%9D%B4%EC%8A%A4+%EB%B8%94%EB%A0%8C%EB%94%94%EB%93%9C_%EC%BB%A4%ED%94%BC%EB%B9%88.jpg"><br><p style="text-align:center">캐러멀 아이스</p><p style="text-align:center">블렌디드</p></div>
        <div style="float:left" class="itemname"><img src="https://s3.ap-northeast-2.amazonaws.com/coffeeinfo/uploads/%ED%97%A4%EC%9D%B4%EC%A6%90%EB%84%9B+%EC%95%84%EC%9D%B4%EC%8A%A4+%EB%B8%94%EB%A0%8C%EB%94%94%EB%93%9C_%EC%BB%A4%ED%94%BC%EB%B9%88.jpg"><br><p style="text-align:center">헤이즐넛 아이스</p><p style="text-align:center">블렌디드</p></div>
        <div style="float:left" class="itemname"><img src="https://s3.ap-northeast-2.amazonaws.com/coffeeinfo/uploads/%ED%99%94%EC%9D%B4%ED%8A%B8+%EC%B5%B8%EC%BD%94%EB%A0%9B+%EB%93%9C%EB%A6%BC+%EC%95%84%EC%9D%B4%EC%8A%A4+%EB%B8%94%EB%A0%8C%EB%94%94%EB%93%9C_%EC%BB%A4%ED%94%BC%EB%B9%88.jpg"><br><p style="text-align:center">화이트 초코렛 드림</p><p style="text-align:center">아이스 블렌디드</p></div>
      </div>
    </div>
    <div class="brands">
      <p><img src="https://s3.ap-northeast-2.amazonaws.com/coffeeinfo/uploads/%ED%88%AC%EC%8D%B8%ED%94%8C%EB%A0%88%EC%9D%B4%EC%8A%A4.jpg"></p>
      <div class="brand">
      </div>
    </div>
  </div>
</div>

<!-- 자바스크립트 -->
<script>
  $(document).ready(function(){
    var $imgs = ["https://s3.ap-northeast-2.amazonaws.com/coffeeinfo/uploads/americano_bback.png",
                "https://s3.ap-northeast-2.amazonaws.com/coffeeinfo/uploads/%EB%8B%88%ED%8A%B8%EB%A1%9C%EC%BD%9C%EB%93%9C%EB%B8%8C%EB%A3%A8_%EC%9A%94%ED%94%84.jpg",
                "https://s3.ap-northeast-2.amazonaws.com/coffeeinfo/uploads/%EB%AA%A8%EC%B9%B4+%EC%95%84%EC%9D%B4%EC%8A%A4+%EB%B8%94%EB%A0%8C%EB%94%94%EB%93%9C+S_%EC%BB%A4%ED%94%BC%EB%B9%88.jpg",
                "https://s3.ap-northeast-2.amazonaws.com/coffeeinfo/uploads/%ED%97%A4%EC%9D%B4%EC%A6%90%EB%84%9B+%EC%95%84%EC%9D%B4%EC%8A%A4+%EB%B8%94%EB%A0%8C%EB%94%94%EB%93%9C_%EC%BB%A4%ED%94%BC%EB%B9%88.jpg",
                "https://s3.ap-northeast-2.amazonaws.com/coffeeinfo/uploads/%EC%BA%90%EB%9F%AC%EB%A9%80+%EC%95%84%EC%9D%B4%EC%8A%A4+%EB%B8%94%EB%A0%8C%EB%94%94%EB%93%9C_%EC%BB%A4%ED%94%BC%EB%B9%88.jpg"
    ];
    var $image = $("#popularMenu");
    var index=0;


      setInterval(function(){
        index++;
        if(index>=$imgs.length){
          index=0;
        }
        $image.attr("src",$imgs[index]);
      },1500);

  })
</script>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to 'Coffee', root_path, id: 'logo' %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Home', home_main_path %></li>

        <li><%= link_to 'Memo', posts_path %></li>

        <li><%= link_to 'Coffee Info', new_post_path %></li>
        <% if user_signed_in?#로그인을 했으면> %>
            <li><%= link_to 'Log out', destroy_user_session_path, method: 'delete' %></li>
        <% else #로그인 안 했으면 %>
            <li><%= link_to 'Log in', new_user_session_path %></li>
        <% end %>


      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CoffeeProject</title>

    <meta name="viewport" content="initial-scale=1.0">
    <meta charset="utf-8">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
    <script
  src="https://code.jquery.com/jquery-3.2.1.min.js"
  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
  crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<div id="menu">
    <nav>
      <ul>
        <li><a href="#">스타벅스</a></li>
        <li><a href="#">이디야</a></li>
        <li><a href="#">커피빈</a></li>
        <li><a href="#">투썸플레이스</a></li>
        <li><a href="#">엔제리너스</a></li>
      </ul>
    </nav>
  </div>
  <div id="line">
  </div>
<p id="notice"><%= notice %></p>

<h1>Coffee Comments</h1>
<form action='posts' method="GET">
  <label>게시글 검색</label>
  <input type="text" name="search">
  <input type="submit" value="검색" class="btn btn-primary">
</form>
<div class="table-responsive">
<table class="table table-fit">
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Email</th>
      <th>Likes</th>
      <th>좋아요 갯수</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= content_tag(:div, post.content.html_safe, :class => "panel-body") %></td>
        <td><%= post.user.email %></td>
        <td><%= post.likes.size %> 명이 좋아합니다.
        <% if current_user.is_like?(post) %>
          <%= link_to "좋아요 취소", post_like_path(post), method: "post" %>
        <% else %>
          <%= link_to "좋아요", post_like_path(post), method: "post" %>
        <% end %>
        </td>
        <td><%= post.likes.count %></td>
        <td><%= link_to 'Show', post %></td>
        <% if current_user == post.user %>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>

    <% end %>
  </tbody>
</table>
<%#= paginate @posts %>
<br>

<p><%= link_to '새 리뷰 작성', new_post_path %></p>
<%= link_to '전체 리뷰 보기', posts_path %>
</div>

app/views/posts/new.html.erb
<h1>Coffee Info</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/reviews/_form.html.erb
<%= form_with(model: review, local: true) do |form| %>
  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, id: :review_user_id %>
  </div>

  <div class="field">
    <%= form.label :coffee_id %>
    <%= form.number_field :coffee_id, id: :review_coffee_id %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :review_title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :review_content %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image, id: :review_image %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location, id: :review_location %>
  </div>

  <div class="field">
    <%= form.label :like_count %>
    <%= form.number_field :like_count, id: :review_like_count %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reviews</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Coffee</th>
      <th>Title</th>
      <th>Content</th>
      <th>Image</th>
      <th>Location</th>
      <th>Like count</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.user_id %></td>
        <td><%= review.coffee_id %></td>
        <td><%= review.title %></td>
        <td><%= review.content %></td>
        <td><%= review.image %></td>
        <td><%= review.location %></td>
        <td><%= review.like_count %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @review.user_id %>
</p>

<p>
  <strong>Coffee:</strong>
  <%= @review.coffee_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @review.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @review.content %>
</p>

<p>
  <strong>Image:</strong>
  <%= @review.image %>
</p>

<p>
  <strong>Location:</strong>
  <%= @review.location %>
</p>

<p>
  <strong>Like count:</strong>
  <%= @review.like_count %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>